// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNkhu990oADs7ygCkJxtXpDgxBsynB_Lk',
    appId: '1:371502319545:web:c688a820a6a69b7bc85868',
    messagingSenderId: '371502319545',
    projectId: 'learningfirebase-f2741',
    authDomain: 'learningfirebase-f2741.firebaseapp.com',
    storageBucket: 'learningfirebase-f2741.appspot.com',
    measurementId: 'G-ZZ5RJ3M733',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkteWj4A0_tZN4yoGZnzeR4urTvjFXa04',
    appId: '1:371502319545:android:8343befa42a428c0c85868',
    messagingSenderId: '371502319545',
    projectId: 'learningfirebase-f2741',
    storageBucket: 'learningfirebase-f2741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVpMOqqtk1JLIzOz7RYHIRqNxHkLth6DA',
    appId: '1:371502319545:ios:6376e02a64100a93c85868',
    messagingSenderId: '371502319545',
    projectId: 'learningfirebase-f2741',
    storageBucket: 'learningfirebase-f2741.appspot.com',
    iosBundleId: 'com.example.learningfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVpMOqqtk1JLIzOz7RYHIRqNxHkLth6DA',
    appId: '1:371502319545:ios:6376e02a64100a93c85868',
    messagingSenderId: '371502319545',
    projectId: 'learningfirebase-f2741',
    storageBucket: 'learningfirebase-f2741.appspot.com',
    iosBundleId: 'com.example.learningfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNkhu990oADs7ygCkJxtXpDgxBsynB_Lk',
    appId: '1:371502319545:web:87ef7cba9c7f23f0c85868',
    messagingSenderId: '371502319545',
    projectId: 'learningfirebase-f2741',
    authDomain: 'learningfirebase-f2741.firebaseapp.com',
    storageBucket: 'learningfirebase-f2741.appspot.com',
    measurementId: 'G-16QPQX3E2M',
  );

}